/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e663feb2ad62b6e6e1d35c556ce20e61)
interface __BaseEnv_Env {
	ENVIRONMENT: "preview" | "production" | "unconfigured";
	ALLOWED_HOSTS: "";
	ACCESS_TEAM_DOMAIN: "";
	ACCESS_AUDIENCE: "";
	PUBLIC_STATUS_URL: "";
	KINETIC_ADMIN_ORIGIN: "";
	PREVIEW_VERIFY_SERVICE_ID: "";
}
declare namespace Cloudflare {
	interface PreviewEnv {
		ENVIRONMENT: "preview";
		ALLOWED_HOSTS: "";
		ACCESS_TEAM_DOMAIN: "";
		ACCESS_AUDIENCE: "";
		PUBLIC_STATUS_URL: "";
		KINETIC_ADMIN_ORIGIN: "";
		PREVIEW_VERIFY_SERVICE_ID: "";
	}
	interface ProductionEnv {
		ENVIRONMENT: "production";
		ALLOWED_HOSTS: "";
		ACCESS_TEAM_DOMAIN: "";
		ACCESS_AUDIENCE: "";
		PUBLIC_STATUS_URL: "";
		KINETIC_ADMIN_ORIGIN: "";
		PREVIEW_VERIFY_SERVICE_ID: "";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ALLOWED_HOSTS" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUDIENCE" | "PUBLIC_STATUS_URL" | "KINETIC_ADMIN_ORIGIN" | "PREVIEW_VERIFY_SERVICE_ID">> {}
}
