/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 76cf4067843bc05883baddfe0b743e76)
interface __BaseEnv_Env {
	ENVIRONMENT: "preview" | "production" | "unconfigured";
	STAFF_AUTH_MODE: "discord";
	DISCORD_REDIRECT_URI: "";
	DISCORD_GUILD_ID: "";
	ALLOWED_HOSTS: "";
	ACCESS_TEAM_DOMAIN: "";
	ACCESS_AUDIENCE: "";
	PUBLIC_STATUS_URL: "";
	KINETIC_ADMIN_ORIGIN: "";
	PREVIEW_VERIFY_SERVICE_ID: "";
	SITE_URL: string;
	PUBLIC_ADMIN_MOCK: string;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		ENVIRONMENT: "preview";
		STAFF_AUTH_MODE: "discord";
		DISCORD_REDIRECT_URI: "";
		DISCORD_GUILD_ID: "";
		ALLOWED_HOSTS: "";
		ACCESS_TEAM_DOMAIN: "";
		ACCESS_AUDIENCE: "";
		PUBLIC_STATUS_URL: "";
		KINETIC_ADMIN_ORIGIN: "";
		PREVIEW_VERIFY_SERVICE_ID: "";
		SITE_URL: string;
		PUBLIC_ADMIN_MOCK: string;
	}
	interface ProductionEnv {
		ENVIRONMENT: "production";
		STAFF_AUTH_MODE: "discord";
		DISCORD_REDIRECT_URI: "";
		DISCORD_GUILD_ID: "";
		ALLOWED_HOSTS: "";
		ACCESS_TEAM_DOMAIN: "";
		ACCESS_AUDIENCE: "";
		PUBLIC_STATUS_URL: "";
		KINETIC_ADMIN_ORIGIN: "";
		PREVIEW_VERIFY_SERVICE_ID: "";
		SITE_URL: string;
		PUBLIC_ADMIN_MOCK: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "STAFF_AUTH_MODE" | "DISCORD_REDIRECT_URI" | "DISCORD_GUILD_ID" | "ALLOWED_HOSTS" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUDIENCE" | "PUBLIC_STATUS_URL" | "KINETIC_ADMIN_ORIGIN" | "PREVIEW_VERIFY_SERVICE_ID" | "SITE_URL" | "PUBLIC_ADMIN_MOCK">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}