// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by wrangler@4.148.0",
  include: [
    "/*"
  ],
  exclude: []
};

// node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "C:\\Users\\mason\\IdeaProjects\\Wilderness-Odyssey\\.wrangler\\tmp\\pages-z05tQ5\\bundledWorker-0.9477400646597917.mjs";
import { isRoutingRuleMatch } from "C:\\Users\\mason\\IdeaProjects\\Wilderness-Odyssey\\node_modules\\wrangler\\templates\\pages-dev-util.ts";
export * from "C:\\Users\\mason\\IdeaProjects\\Wilderness-Odyssey\\.wrangler\\tmp\\pages-z05tQ5\\bundledWorker-0.9477400646597917.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=zoxh3sdant.js.map
