# CropCritters Configuration
# Config changes only apply on restart
# 
# Weed percentage grow chances:
regularWeedsGrowChance = 3
netherWeedsGrowChance = 4
# Should monocultures have increased weed chances:
monoculturePenalize = true
# 
# How far should Mazewood spread (1-128):
# (Be careful, spreads fast) 
mazewoodSpread = 4
# 
# Lost soul mob drop chance:
lostSoulDropChance = 6
# 
# Crop critter spawn chance on crop just matured
# or on randomTick in SoulSandValley.
# Chance doubled if on a 'Soul' block:
critterSpawnChance = 8
# 
# Multiplier on critter work speed:
# (Between 0.01 and 10.0)
critterWorkSpeedMultiplier = 1.0
# 
# Biome generation toggles: 
deadCoralGeneration = true
soulRoseHintGeneration = true
thornweedGeneration = true
waftgrassGeneration = true
spiteweedGeneration = true
strangleFernGeneration = true
puffbombGeneration = true
liverwortGeneration = true
# 
# Copper Soul Rose crop growth rate slowdown (percentage): 
copperSoulRoseSlowdown = 25
