#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Feb 02 23:42:25 EST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Bliss-Shader-main.zip
