#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jan 13 23:31:47 EST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Mellow v2.2.1.zip
