#Maximum energy storage capacity of the Shell Forge
# Default: 1000000
# Range: > 1
shellForgeEnergyCapacity = 1000000
#Energy consumed by the Shell Forge to create a single Shell (must not exceed the energy capacity)
# Default: 1000000
# Range: > 1
shellForgeEnergyUsageCreation = 1000000
#Energy consumed by the Shell Forge per tick to maintain an alive Shell (must not exceed the energy capacity)
#If you want to disable decaying, simply set this value to 0
# Default: 1000
# Range: > 0
shellForgeEnergyUsageMaintenance = 1000
#Time required to progress by 1% during Shell creation (in ticks)
# Default: 20
# Range: > 1
shellForgeCreationCooldown = 20
#Time required to progress by 1% during Shell decay (in ticks)
# Default: 10
# Range: > 1
shellForgeDecayCooldown = 10
#Maximum energy storage capacity of the Centrifuge
# Default: 100000
# Range: > 1
centrifugeEnergyCapacity = 100000
#Energy consumed by the Centrifuge per tick
# Default: 3000
# Range: > 1
centrifugeEnergyUsage = 3000
#If enabled, the player will respawn in the nearest shell after death, even in hardcore mode. When disabled, death in hardcore mode remains permanent
transferIntoShellAfterDeath = true
