#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			spirit = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			spirit = true
			flowering_spirit = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

#Disables specific entries
[entries]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			couch = true
			shelf = true
			nightstand = true
			table = true
			chair = true
			drawer = true
			cupboard = true
			pillar_trim = true
			dining_bench = true
			side_table = true
			bench = true

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.farmersdelight]
			cabinet = true
