#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Nov 25 12:25:54 EST 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=BSL_v8.4.zip
