#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jan 23 13:35:59 EST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.4 + EuphoriaPatches_1.5.0
