#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jan 22 21:13:08 EST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.4 + EuphoriaPatches_1.5.0
